# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt/EasyMoney/MainWindow.ui'
#
# Created: Sun Apr 12 19:04:12 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(801, 704)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout()
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.horizontalLayoutTop = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTop.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayoutTop.setObjectName("horizontalLayoutTop")
        self.sel_Import = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sel_Import.sizePolicy().hasHeightForWidth())
        self.sel_Import.setSizePolicy(sizePolicy)
        self.sel_Import.setSizeIncrement(QtCore.QSize(0, 0))
        self.sel_Import.setBaseSize(QtCore.QSize(0, 0))
        self.sel_Import.setObjectName("sel_Import")
        self.sel_Import.addItem("")
        self.horizontalLayoutTop.addWidget(self.sel_Import)
        self.btn_New = QtWidgets.QPushButton(self.centralWidget)
        self.btn_New.setObjectName("btn_New")
        self.horizontalLayoutTop.addWidget(self.btn_New)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutTop)
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setMinimumSize(QtCore.QSize(256, 0))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayoutMain.addWidget(self.tableWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutMain.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_Comment = QtWidgets.QLineEdit(self.centralWidget)
        self.txt_Comment.setObjectName("txt_Comment")
        self.horizontalLayout.addWidget(self.txt_Comment)
        self.sel_Accounts = QtWidgets.QComboBox(self.centralWidget)
        self.sel_Accounts.setFrame(False)
        self.sel_Accounts.setObjectName("sel_Accounts")
        self.sel_Accounts.addItem("")
        self.horizontalLayout.addWidget(self.sel_Accounts)
        self.btn_AutoInfo = QtWidgets.QPushButton(self.centralWidget)
        self.btn_AutoInfo.setObjectName("btn_AutoInfo")
        self.horizontalLayout.addWidget(self.btn_AutoInfo)
        self.btn_Save = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Save.setEnabled(True)
        self.btn_Save.setFlat(False)
        self.btn_Save.setObjectName("btn_Save")
        self.horizontalLayout.addWidget(self.btn_Save)
        self.verticalLayoutMain.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayoutMain)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setToolTip("")
        self.statusBar.setStatusTip("")
        self.statusBar.setAccessibleDescription("")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.sel_Accounts.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Easy Money"))
        self.sel_Import.setItemText(0, _translate("MainWindow", "Item1"))
        self.btn_New.setText(_translate("MainWindow", "New"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "WAAA"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Category"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ignore"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "2015-01-11"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Pengar"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "-123.3"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "Swedbank"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "123.4"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.txt_Comment.setText(_translate("MainWindow", "Import comment text"))
        self.sel_Accounts.setItemText(0, _translate("MainWindow", "Swedbank", "Bank1"))
        self.btn_AutoInfo.setText(_translate("MainWindow", "Autoinfo"))
        self.btn_Save.setText(_translate("MainWindow", "Save"))

